server:
  port: 9004   # ForsÃ©ti en 9004

spring:
  mvc:
    problemdetails:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/touristchaindb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: Tiuristchain        # ðŸ‘ˆ pon aquÃ­ tu usuario de MySQL
    password: "Touristchain2024!Secure#"        # ðŸ‘ˆ pon aquÃ­ tu clave de MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver

forseti:
  api-prefix: /api/v1/forseti   # prefijo oficial para ForsÃ©ti

cors:
  allowed-origins: http://localhost:8080
